version: "3"

services:
  app:
    image: quay.io/keycloak/keycloak:15.0.0
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - "8081:8080"